#--------------------------------------------------------------------------
# Change the value of TRILINOS_INSTALL_DIR to point to the directory
# into which you have installed Trilinos. For example, if you have
# installed into /usr/local/trilinos-3.14.59, change this line to
#
# TRILINOS_INSTALL_DIR = /usr/local/trilinos-3.14.59 
#
#--------------------------------------------------------------------------

TRILINOS_INSTALL_DIR = $(HOME)/Code/TTUTrilinos/BUILDS/GCC-OPT

#--------------------------------------------------------------------------
# If your application contains more than one source file, list any additional
# object files in the variable EXTRA_OBJS, e.g.,
# 
# EXTRA_OBJS = SomeFile.o SomeOtherFile.o
# 
#--------------------------------------------------------------------------



#--------------------------------------------------------------------------
# The remaining lines will not usually need to be changed.  
#--------------------------------------------------------------------------

INC = ../lib
LIB_SRCS = $(wildcard ../lib/*.cpp)
LIB_OBJS = $(patsubst ../lib/%.cpp, ../lib/%.o, $(LIB_SRCS))

include $(TRILINOS_INSTALL_DIR)/include/Makefile.export.Sundance

Sundance_LIB_PATH = $(TRILINOS_INSTALL_DIR)/lib
Sundance_INCLUDE_PATH = $(TRILINOS_INSTALL_DIR)/include

%.exe : %.o $(LIB_OBJS) $(EXTRA_OBJS)
	$(Sundance_CXX_COMPILER) -o $@ $(LDFLAGS) $(Sundance_CXX_FLAGS) $< $(LIB_OBJS) $(EXTRA_OBJS) $(Sundance_SHARED_LIB_RPATH_COMMAND) -L$(Sundance_LIB_PATH) $(Sundance_LIBRARIES) $(Sundance_TPL_LIBRARIES) $(Sundance_EXTRA_LD_FLAGS)

%.o : %.cpp $(EXTRA_INCS)
	$(Sundance_CXX_COMPILER) -c -o $@ $(Sundance_CXX_FLAGS) -I$(INC) -I$(Sundance_INCLUDE_PATH) $(Sundance_TPL_INCLUDES) $<

../lib/%.o : ../lib/%.cpp
	$(Sundance_CXX_COMPILER) -c -o $@ $(Sundance_CXX_FLAGS) -I$(INC) -I$(Sundance_INCLUDE_PATH) $(Sundance_TPL_INCLUDES) $<
